<?php
// db_dump.php (VERZE BEZ ADMIN HESLA)
// Poznámka: přístup k tomuto souboru omezíš pomocí .htaccess (viz níže).

// ===== Nastavení =====
$DUMPS_DIR      = __DIR__ . '/dumps';            // složka pro výstupy
$GZIP_OUTPUT    = true;                          // true = .sql.gz, false = .sql
$BATCH_SIZE     = 200;                           // kolik řádků na jeden INSERT
$LOG_FILE       = __DIR__ . '/dump_error.log';   // kam logovat chyby (není veřejné)

// Zapni víc chyb pro ladění (klidně vypni po zprovoznění)
error_reporting(E_ALL & ~E_NOTICE);
ini_set('display_errors', '0'); // chyby do logu, ne do výstupu

function log_err($msg) {
    global $LOG_FILE;
    @file_put_contents($LOG_FILE, '['.date('c')."] $msg\n", FILE_APPEND);
}

function bt($s){ return '`' . str_replace('`','``',$s) . '`'; }

function safe_filename($name) {
    return preg_replace('/[^A-Za-z0-9_\-\.]/', '_', $name);
}

function write_all($h, $str) {
    $len = strlen($str);
    $w = 0;
    while ($w < $len) {
        $n = @fwrite($h, substr($str, $w));
        if ($n === false) return false;
        $w += $n;
    }
    return true;
}

// Diagnostika: ?diag=1
if (isset($_GET['diag'])) {
    header('Content-Type: text/plain; charset=utf-8');
    echo "Diagnostika prostredi\n";
    echo (is_dir($DUMPS_DIR) ? "✔ Slozka dumps existuje ($DUMPS_DIR)\n" : "✖ Slozka dumps NEEXISTUJE ($DUMPS_DIR)\n");
    echo (is_writable($DUMPS_DIR) ? "✔ Slozka dumps je zapisovatelna\n" : "✖ Slozka dumps NENI zapisovatelna\n");
    echo (function_exists('mysqli_connect') ? "✔ mysqli je k dispozici\n" : "✖ mysqli NENI k dispozici\n");
    echo ((function_exists('gzopen') || !$GZIP_OUTPUT) ? "✔ zlib pro gzip OK (nebo gzip vypnut)\n" : "✖ chybi zlib (zapni \$GZIP_OUTPUT=false)\n");
    echo "max_execution_time = " . ini_get('max_execution_time') . "\n";
    echo "memory_limit       = " . ini_get('memory_limit') . "\n";
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // BEZ ADMIN HESLA — pozor: přístup musí být omezen .htaccess nebo jinak
    $db_host = trim($_POST['host'] ?? 'localhost');
    $db_port = (int)($_POST['port'] ?? 3306);
    $db_user = trim($_POST['user'] ?? '');
    $db_pass = $_POST['pass'] ?? '';
    $db_name = trim($_POST['db'] ?? '');
    $tables_input = trim($_POST['tables'] ?? '');
    $structure_only = isset($_POST['structure_only']) && $_POST['structure_only'] === '1';

    if ($db_user === '' || $db_name === '') {
        echo "Uživatelské jméno a název DB jsou povinné.";
        exit;
    }

    if (!is_dir($DUMPS_DIR)) {
        @mkdir($DUMPS_DIR, 0775, true);
    }
    if (!is_writable($DUMPS_DIR)) {
        echo "Složka 'dumps' není zapisovatelná: " . htmlspecialchars($DUMPS_DIR);
        exit;
    }

    // Připojení
    mysqli_report(MYSQLI_REPORT_OFF);
    $mysqli = @new mysqli($db_host, $db_user, $db_pass, $db_name, $db_port);
    if ($mysqli->connect_errno) {
        log_err("Connect error ({$mysqli->connect_errno}): {$mysqli->connect_error}");
        echo "Chyba připojení k DB. Podrobnosti jsou v logu.";
        exit;
    }
    $mysqli->set_charset('utf8mb4');

    // Seznam tabulek
    $tables = [];
    if ($tables_input !== '') {
        foreach (explode(',', $tables_input) as $p) {
            $p = trim($p);
            if ($p !== '') $tables[] = $p;
        }
    } else {
        $res = $mysqli->query("SHOW FULL TABLES");
        if (!$res) {
            log_err("SHOW FULL TABLES fail: ".$mysqli->error);
            echo "Nelze získat seznam tabulek (viz log).";
            exit;
        }
        while ($row = $res->fetch_array(MYSQLI_NUM)) {
            $tables[] = $row[0];
        }
        $res->free();
    }

    if (!$tables) {
        echo "Žádné tabulky k exportu.";
        exit;
    }

    $timestamp = date('Ymd_His');
    $base = safe_filename($db_name . '_' . $timestamp);
    $target_path = $DUMPS_DIR . '/' . $base . ($GZIP_OUTPUT ? '.sql.gz' : '.sql');

    // Otevřeme výstup
    $fh = null;
    if ($GZIP_OUTPUT) {
        if (!function_exists('gzopen')) {
            echo "Na serveru chybí zlib (pro .gz). Nastav \$GZIP_OUTPUT=false nebo povol zlib.";
            exit;
        }
        $fh = @gzopen($target_path, 'wb9');
    } else {
        $fh = @fopen($target_path, 'wb');
    }
    if (!$fh) {
        echo "Nelze otevřít výstupní soubor: " . htmlspecialchars($target_path);
        exit;
    }

    // Helpery pro zápis
    $write = function($s) use ($fh, $GZIP_OUTPUT) {
        if ($GZIP_OUTPUT) return @gzwrite($fh, $s) !== false;
        else return write_all($fh, $s);
    };
    $close = function() use ($fh, $GZIP_OUTPUT) {
        if ($GZIP_OUTPUT) @gzclose($fh);
        else @fclose($fh);
    };

    @set_time_limit(0);
    @ignore_user_abort(true);

    // Hlavička dumpu
    $write("-- SQL dump generated by db_dump.php\n");
    $write("-- Host: {$db_host}  Database: {$db_name}\n");
    $write("-- Generation time: " . date('r') . "\n\n");
    $write("/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;\n");
    $write("/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;\n");
    $write("/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;\n");
    $write("SET NAMES utf8mb4;\nSET FOREIGN_KEY_CHECKS=0;\n\n");

    // Export tabulek
    foreach ($tables as $table) {
        // CREATE TABLE / VIEW
        $res = $mysqli->query("SHOW CREATE TABLE ".bt($table));
        if (!$res) {
            // může jít o VIEW → zkus SHOW CREATE VIEW
            $res2 = $mysqli->query("SHOW CREATE VIEW ".bt($table));
            if (!$res2) {
                log_err("SHOW CREATE (table/view) fail for $table: ".$mysqli->error);
                $write("-- CHYBA: nelze ziskat CREATE pro ".bt($table)."\n\n");
                continue;
            }
            $row = $res2->fetch_assoc();
            $create_stmt = $row['Create View'] ?? null;
            $res2->free();
        } else {
            $row = $res->fetch_assoc();
            $create_stmt = $row['Create Table'] ?? null;
            $res->free();
        }

        if (!$create_stmt) {
            log_err("CREATE statement missing for $table");
            $write("-- CHYBA: CREATE statement chybi pro ".bt($table)."\n\n");
            continue;
        }

        $write("-- --------------------------------------------------------\n");
        $write("-- Structure for ".bt($table)."\n");
        $write("-- --------------------------------------------------------\n\n");
        $write("DROP TABLE IF EXISTS ".bt($table).";\n");
        $write($create_stmt . ";\n\n");

        if ($structure_only) continue;

        // Spočítáme řádky (nepovinné)
        $totalRows = 0;
        if ($cnt = $mysqli->query("SELECT COUNT(*) AS c FROM ".bt($table))) {
            $c = $cnt->fetch_assoc();
            $totalRows = (int)$c['c'];
            $cnt->free();
        }
        if ($totalRows === 0) {
            $write("-- Table ".bt($table)." is empty.\n\n");
            continue;
        }
        $write("-- Data for ".bt($table)." ($totalRows rows)\n");

        // Sloupce
        $cols = [];
        if ($cr = $mysqli->query("SHOW COLUMNS FROM ".bt($table))) {
            while($c = $cr->fetch_assoc()) $cols[] = $c['Field'];
            $cr->free();
        } else {
            log_err("SHOW COLUMNS fail for $table: ".$mysqli->error);
            $write("-- CHYBA: SHOW COLUMNS selhalo pro ".bt($table)."\n\n");
            continue;
        }
        $colList = implode(', ', array_map('bt', $cols));

        // Unbuffered SELECT pro nižší paměť
        if (!$mysqli->real_query("SELECT * FROM ".bt($table))) {
            log_err("SELECT * fail for $table: ".$mysqli->error);
            $write("-- CHYBA: SELECT selhal pro ".bt($table)."\n\n");
            continue;
        }
        $result = $mysqli->use_result();
        if (!$result) {
            log_err("use_result fail for $table: ".$mysqli->error);
            $write("-- CHYBA: use_result selhalo pro ".bt($table)."\n\n");
            continue;
        }

        $batch = [];
        $count = 0;
        while ($row = $result->fetch_assoc()) {
            $vals = [];
            foreach ($cols as $c) {
                if (!isset($row[$c]) || $row[$c] === null) {
                    $vals[] = "NULL";
                } else {
                    $v = $mysqli->real_escape_string($row[$c]);
                    $vals[] = "'".$v."'";
                }
            }
            $batch[] = '('.implode(', ', $vals).')';

            if (count($batch) >= $BATCH_SIZE) {
                $write("INSERT INTO ".bt($table)." ($colList) VALUES\n".implode(",\n",$batch).";\n");
                $batch = [];
            }
        }
        if (count($batch) > 0) {
            $write("INSERT INTO ".bt($table)." ($colList) VALUES\n".implode(",\n",$batch).";\n");
        }
        $write("\n");
        $result->free();
    }

    // Paticka
    $write("SET FOREIGN_KEY_CHECKS=1;\n");
    $write("/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;\n");
    $write("/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;\n");
    $write("/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;\n");

    $close();
    $mysqli->close();

    // Hotovo – nabídni link ke stažení (upravený vzhled, lepší zalamování + tlačítko zpět)
$public_rel = 'dumps/' . basename($target_path);
$nice_name  = basename($target_path);
?>
<!doctype html>
<html lang="cs">
<head>
<meta charset="utf-8">
<title>Dump databáze dokončen</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
  :root{
    --brand:#0b74de;
    --text:#222;
    --muted:#555;
    --bg:#eef2f6;
  }
  body{
    font-family:system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial;
    background:var(--bg);
    margin:0;padding:24px;
    display:flex;justify-content:center;align-items:center;
    min-height:100vh;
  }
  .card{
    background:#fff;
    padding:32px;
    border-radius:14px;
    box-shadow:0 6px 18px rgba(0,0,0,.12);
    max-width:760px;
    width:100%;
    text-align:center;
  }
  h1{color:var(--brand);font-size:1.9rem;margin:0 0 10px 0}
  p{margin:12px 0;color:var(--text);line-height:1.5}
  .actions{margin:18px 0 8px;display:flex;flex-direction:column;gap:12px;align-items:center}
  a.btn, a.back-btn{
    display:inline-block;
    padding:12px 22px;
    border-radius:10px;
    font-weight:700;
    text-decoration:none;
    transition:filter .15s;
  }
  a.btn{
    background:var(--brand);
    color:#fff;
  }
  a.btn:hover{filter:brightness(0.95)}
  a.back-btn{
    background:#f3f4f6;
    color:var(--text);
    border:1px solid #d0d7de;
  }
  a.back-btn:hover{background:#e5e7eb}
  .grid{
    display:grid;
    grid-template-columns:1fr auto;
    gap:10px 12px;
    align-items:start;
    margin-top:14px;
    text-align:left;
  }
  .label{color:var(--muted);font-size:.95rem;margin-top:2px}
  .value{
    font: 500 0.98rem/1.45 ui-monospace, SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace;
    color:var(--text);
    background:#f7f8fa;
    border:1px solid #e5e7eb;
    border-radius:8px;
    padding:10px 12px;
    overflow-wrap:anywhere;
    word-break:break-word;
    white-space:pre-wrap;
  }
  .copy-btn{
    padding:8px 12px;
    border:1px solid #d0d7de;
    border-radius:8px;
    background:#fff;
    cursor:pointer;
    font-weight:600;
  }
  .copy-btn:hover{background:#f3f4f6}
  .hint{color:var(--muted);font-size:.95rem;margin-top:14px}
</style>
</head>
<body>
  <div class="card">
    <h1>Dump hotový ✅</h1>
    <p>Soubor databáze byl úspěšně vytvořen.</p>

    <div class="actions">
      <a class="btn" href="<?=htmlspecialchars($public_rel)?>" download>
        Stáhnout dump<br><small><?=htmlspecialchars($nice_name)?></small>
      </a>
      <a class="back-btn" href="db_dump.php">⬅ Zpět na hlavní stránku</a>
    </div>

    <div class="grid">
      <div class="label">Uložen:</div>
      <div class="value" id="pathDump"><?=htmlspecialchars($public_rel)?></div>
      <div></div>
      <div><button class="copy-btn" onclick="copyText('pathDump')">Kopírovat</button></div>

      <div class="label">Log chyb:</div>
      <div class="value" id="pathLog"><?=htmlspecialchars($LOG_FILE)?></div>
      <div></div>
      <div><button class="copy-btn" onclick="copyText('pathLog')">Kopírovat</button></div>
    </div>

    <p class="hint">Po stažení doporučuji dump smazat (případně dočasně zakázat přístup do složky <code>dumps/</code>).</p>
  </div>

<script>
  function copyText(id){
    const el = document.getElementById(id);
    if(!el) return;
    const txt = el.innerText;
    navigator.clipboard?.writeText(txt).catch(()=>{
      const ta=document.createElement('textarea');
      ta.value=txt;document.body.appendChild(ta);
      ta.select();document.execCommand('copy');
      document.body.removeChild(ta);
    });
  }
</script>
</body>
</html>
<?php
exit;
}

// HTML form (bez admin hesla)
?>
<!doctype html>
<html lang="cs">
<head>
<meta charset="utf-8">
<title>Bezpečný MariaDB dump (na disk)</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial;max-width:900px;margin:20px auto;padding:16px}
label{display:block;margin:8px 0 4px}
input[type=text], input[type=password]{width:100%;padding:8px;border:1px solid #ccc;border-radius:6px}
button{padding:10px 16px;border-radius:8px;background:#0b74de;color:#fff;border:0;cursor:pointer}
small{color:#666}
.container{background:#f9f9f9;padding:16px;border-radius:8px;box-shadow:0 1px 3px rgba(0,0,0,.05)}
</style>
</head>
<body>
<div class="container">
<h2>SQL dump</h2>

<form method="post">
    <label>Host</label>
    <input type="text" name="host" value="localhost" required>

    <label>Port</label>
    <input type="text" name="port" value="3306">

    <label>Uživatel</label>
    <input type="text" name="user" required>

    <label>Heslo</label>
    <input type="password" name="pass">

    <label>Databáze</label>
    <input type="text" name="db" required>

    <label>Tabulky (volitelné, oddělit čárkou)</label>
    <input type="text" name="tables" placeholder="např. users,posts (prázdné = všechny)">

    <label><input type="checkbox" name="structure_only" value="1"> Pouze struktura (bez dat)</label>

    <p><small>Diagnostika prostředí: přidej do URL <code>?diag=1</code></small></p>
    <button type="submit">Vytvořit dump</button>
</form>
</div>
</body>
</html>